import React,{useEffect,useState} from 'react';
import {configCall,photoUrl} from './RuleSamples';
import {Icon} from './icons';

export const imageStatus={pending:'待分析',analyzing:'分析中',completed:'已完成',failed:'分析失败',pass:'通过',fail:'不通过',review:'人工核查',need_photo:'待补充照片'};
export function imageProgress(task){const total=task.rule.items.length;return task.status==='completed'?100:Math.round(Object.keys(task.results||{}).length/Math.max(1,total)*100);}
const Button=({children,...props})=><button type="button" className="button secondary" {...props}>{children}</button>;
function ImageFilePreview({file,onRemove,disabled}) {
 const [url,setUrl]=useState('');
 useEffect(()=>{const next=URL.createObjectURL(file);setUrl(next);return()=>URL.revokeObjectURL(next);},[file]);
 return <div className="image-upload-file"><img src={url} alt={file.name}/><div><strong title={file.name}>{file.name}</strong><small>{(file.size/1024/1024).toFixed(2)} MB</small></div><button type="button" aria-label={`移除 ${file.name}`} disabled={disabled} onClick={onRemove}><Icon name="close" size={16}/></button></div>;
}
export function ImageUploadPage({bootstrap,navigate,disabled=false}){
 const [configs,setConfigs]=useState([]),[configId,setConfigId]=useState(''),[store,setStore]=useState(bootstrap?.store?.name||'MOMOYO JTU'),[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{configCall('/configs').then(rows=>setConfigs(rows.filter(r=>r.type==='image'&&(r.params?.inputType||'image')==='image'&&r.photoItems?.length))).catch(e=>setError(e.message));},[]);
 const selected=configs.find(r=>r.id===configId);
 async function submit(){setBusy(true);setError('');try{
   const rule=await configCall('/rules','POST',{name:selected.name,items:selected.photoItems,source_config_id:selected.id,source_config_version:selected.version});
   let first;
   for(const file of files){const photo=await configCall('/photos','POST',file);const task=await configCall('/tasks','POST',{rule_id:rule.id,store:store.trim(),sample_name:file.name});await configCall('/tasks/'+task.id+'/photos','PUT',Object.fromEntries(rule.items.map(i=>[i.id,photo.id])));first ||= task.id;}
   navigate('imageTask',first);
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="surface image-upload-page"><div className="page-section-title"><div><h2>图片上传</h2><p>选择核验规则，上传菜单、物料或门店照片</p></div><Button onClick={()=>navigate('runs')}>查看分析任务</Button></div>{error&&<p role="alert" className="error-text">{error}</p>}{disabled&&<p>线上演示暂不开放图片上传与 AI 分析。</p>}<div className="image-upload-form"><label>门店<input value={store} disabled={busy||disabled} onChange={e=>setStore(e.target.value)}/></label><label>检测规则<select value={configId} disabled={busy||disabled} onChange={e=>setConfigId(e.target.value)}><option value="">请选择图片核验规则</option>{configs.map(r=><option key={r.id} value={r.id}>{r.code} · {r.name} · {r.version}{r.status==='draft'?' · 草稿':''}</option>)}</select></label>{!configs.length&&<p>暂无图片规则，请在规则配置中添加图片检查项。</p>}{selected&&<div className="image-rule-summary"><strong>核验标准</strong>{selected.photoItems.map(i=><div key={i.id}><strong>{i.name}{i.required?' · 必检':''}</strong><p>{i.standard}</p>{i.photo_hint&&<small>{i.photo_hint}</small>}</div>)}</div>}<label className={`image-upload-dropzone ${busy||disabled?"is-disabled":""}`}><span className="image-upload-symbol"><Icon name="image" size={28}/></span><strong>{files.length?"重新选择图片":"点击上传门店图片"}</strong><span>菜单、物料、陈列等场景，按所选规则逐项核验</span><small>支持 JPG、PNG · 单张最大 10 MB · 最多 10 张</small><span className="image-upload-pick">选择图片</span><input type="file" multiple accept="image/png,image/jpeg" disabled={busy||disabled} onChange={e=>{const chosen=Array.from(e.target.files||[]);if(chosen.length>10||chosen.some(f=>f.size>10*1024*1024)){setError('最多选择10张图片，每张不超过10MB');setFiles([]);return;}setError('');setFiles(chosen);}}/></label>{files.length>0&&<div className="image-file-list">{files.map((f,index)=><ImageFilePreview key={f.name+f.size+index} file={f} disabled={busy} onRemove={()=>setFiles(current=>current.filter((_,i)=>i!==index))}/>)}</div>}<button className="button primary" disabled={disabled||busy||!selected||!store.trim()||!files.length||selected.photoItems.some(i=>!i.name||!i.standard)} onClick={submit}>{busy?'正在上传…':'上传并创建分析任务'}</button><p className="image-upload-note">每张图片生成独立任务，上传后可在详情页开始 AI 核验。</p></div></section>;
}
export function ImageTaskList({navigate}){
 const [tasks,setTasks]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all');
 const refresh=()=>configCall('/tasks').then(t=>{setTasks([...t].sort((a,b)=>(Date.parse(b.created_at||b.completed_at)||0)-(Date.parse(a.created_at||a.completed_at)||0)));setError('');}).catch(e=>setError(e.message));
 useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer);},[]);
 const visible=(tasks||[]).filter(t=>(status==='all'||t.status===status)&&[t.id,t.rule.name,t.store,t.sample_name].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <section className="surface list-page image-task-list"><div className="page-section-title"><div><h2>图片识别任务</h2><p>查看门店图片、识别进度与逐项核验结论</p></div><div><Button onClick={refresh}>刷新</Button> <Button onClick={()=>navigate('imageUpload')}>上传图片</Button></div></div>{error&&<p role="alert" className="error-text">{error}</p>}<div className="rectification-filters"><select aria-label="图片任务状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option>{['pending','analyzing','completed','failed'].map(s=><option key={s} value={s}>{imageStatus[s]}</option>)}</select><input aria-label="搜索图片任务" placeholder="任务 ID / 图片 / 规则 / 门店" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="image-task-table"><div className="table-head image-task-row"><span>任务 / 图片 / 门店</span><span>检测规则</span><span>处理进度</span><span>核验结果 / 状态</span><span>耗时 / 调用 / Token</span><span>分析时间</span></div>{visible.map(t=><button type="button" className="table-row image-task-row" key={t.id} onClick={()=>navigate('imageTask',t.id)}><div><strong>{t.id}</strong><span>{t.sample_name||'门店图片'}</span><small>{t.store}</small></div><span>{t.rule.name}</span><span>{imageProgress(t)}% · {Object.keys(t.results||{}).length}/{t.rule.items.length} 项</span><div><strong className={t.conclusion==='fail'?'error-text':''}>{imageStatus[t.conclusion]||'等待核验'}</strong><span>{imageStatus[t.status]}</span></div><span>{t.active_seconds==null?"耗时未记录":`${Math.round(t.active_seconds)} 秒`}<br/>{(t.usage||[]).length} 次 / {(t.usage||[]).reduce((sum,u)=>sum+(u.total_tokens||0),0).toLocaleString()} Token</span><time>{t.completed_at?new Date(t.completed_at).toLocaleString("zh-CN",{hour12:false}):t.started_at?new Date(t.started_at).toLocaleString("zh-CN",{hour12:false}):"尚未分析"}<small>{t.created_at?`创建 ${new Date(t.created_at).toLocaleString("zh-CN",{hour12:false})}`:"创建时间未记录"}</small></time></button>)}{!visible.length&&<p className="table-empty">{tasks===null?'正在加载图片任务…':'暂无符合条件的图片任务'}</p>}</div></section>;
}
export function ImageTaskDetail({id,navigate,disabled=false}){
 const [task,setTask]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>configCall('/tasks').then(rows=>{const found=rows.find(t=>t.id===id);if(!found)throw Error('图片任务不存在');setTask(found);}).catch(e=>setError(e.message));
 useEffect(()=>{refresh();const timer=setInterval(refresh,3000);return()=>clearInterval(timer);},[id]);
 async function analyze(){setBusy(true);setError('');try{setTask(await configCall('/tasks/'+id+'/analyze','POST'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><Button onClick={()=>navigate('runs')}>返回分析任务</Button>{error&&<p role="alert" className="error-text">{error}</p>}{task?<><section className="surface image-task-heading"><h2>{task.rule.name}</h2><p>{task.store} · {task.sample_name} · {task.id}</p><strong className={task.conclusion==='fail'?'image-result-fail':''}>{imageStatus[task.conclusion]||imageStatus[task.status]} · {imageProgress(task)}%</strong><p>规则版本 {task.rule.source_config_version||task.rule.version} · 已核验 {Object.keys(task.results||{}).length}/{task.rule.items.length} 项</p>{task.error&&<p className="error-text">{task.error}</p>}{['pending','failed'].includes(task.status)&&<button className="button primary" disabled={disabled||busy} onClick={analyze}>{busy?'分析中…':task.status==='failed'?'重试 AI 核验':'开始 AI 核验'}</button>}{task.status==='analyzing'&&<p role="status">AI 正在逐项核验，可返回列表查看进度。</p>}</section><div className="image-detail-items">{task.rule.items.map(item=><section className="surface image-detail-item" key={item.id}><h3>{item.name}{item.required?' · 必检':''}</h3><p>标准：{item.standard}</p><div className="image-evidence-pair">{item.reference_id&&<figure><figcaption>标准参考图 · 点击放大</figcaption><a href={photoUrl(item.reference_id)} target="_blank" rel="noreferrer"><img alt="标准参考图" src={photoUrl(item.reference_id)}/></a></figure>}{task.photos[item.id]?<figure><figcaption>门店提交图片 · 点击放大</figcaption><a href={photoUrl(task.photos[item.id])} target="_blank" rel="noreferrer"><img alt="门店提交图片" src={photoUrl(task.photos[item.id])}/></a></figure>:<p>缺少检查照片</p>}</div><strong className={task.results[item.id]?.status==='fail'?'error-text':''}>{imageStatus[task.results[item.id]?.status]||'待核验'}</strong><p>{task.results[item.id]?.reason}</p></section>)}</div></>:<section className="surface image-task-heading">{error?'无法读取图片任务':'正在加载…'}</section>}</>;
}
