import React,{useState,useEffect} from 'react';
import {apiUrl} from './api';
const labels={pass:'通过',fail:'不通过',review:'人工核查',need_photo:'待补充照片',pending:'待上传',analyzing:'分析中',completed:'已完成',failed:'分析失败'};
async function call(path,method='GET',body){const raw=body instanceof File;const res=await fetch(apiUrl('/api/image-checks'+path),{method,headers:body&&!raw?{'content-type':'application/json'}:{},body:body?(raw?body:JSON.stringify(body)):undefined});const data=await res.json();if(!res.ok)throw Error(typeof data.detail==='string'?data.detail:'请求失败，请检查配置');return data;}
export default function ImageChecks({canAdmin,disabled}){
 const [rules,setRules]=useState([]),[tasks,setTasks]=useState([]),[name,setName]=useState(''),[items,setItems]=useState([{id:'item-1',name:'',standard:'',required:true,photo_hint:'',reference_id:null}]),[ruleId,setRuleId]=useState(''),[store,setStore]=useState('MOMOYO JTU'),[task,setTask]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){const [r,t]=await Promise.all([call('/rules'),call('/tasks')]);setRules(r);setTasks(t);}
 useEffect(()=>{if(!disabled)refresh().catch(e=>setError(e.message));},[disabled]);
 async function act(fn){setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function edit(i,key,value){setItems(old=>old.map((x,j)=>i===j?{...x,[key]:value}:x));}
 return <section className="surface image-checks"><div className="page-section-title"><div><h2>图片核验</h2><p>配置标准 · 门店拍照 · AI 逐项核验</p></div></div>{disabled?<p>线上展示版本暂不开放图片上传与分析，请在本地服务使用。</p>:<>
 {error&&<p role="alert" className="error-text">{error}</p>}
 {canAdmin&&<details><summary>新建图片核验规则</summary><label>规则名称<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如新品布置、陈列或标签检查" /></label>{items.map((it,i)=><fieldset key={it.id}><legend>检查项 {i+1}</legend><label>名称<input value={it.name} onChange={e=>edit(i,'name',e.target.value)} /></label><label>通过标准<textarea value={it.standard} onChange={e=>edit(i,'standard',e.target.value)} placeholder="说明需要观察什么、符合什么条件" /></label><label>拍摄要求<input value={it.photo_hint} onChange={e=>edit(i,'photo_hint',e.target.value)} /></label><label><input type="checkbox" checked={it.required} onChange={e=>edit(i,'required',e.target.checked)} />必检项</label><label>参考图（可选）<input type="file" accept="image/png,image/jpeg" disabled={busy} onChange={e=>{const file=e.target.files[0];if(file)act(async()=>{const p=await call('/photos','POST',file);edit(i,'reference_id',p.id);});}} /></label>{it.reference_id&&<img alt="标准参考图" src={apiUrl('/api/image-checks/photos/'+it.reference_id)} />}</fieldset>)}<button disabled={busy||items.length>=20} onClick={()=>setItems([...items,{id:'item-'+Date.now(),name:'',standard:'',required:true,photo_hint:'',reference_id:null}])}>添加检查项</button><button disabled={busy||!name||items.some(i=>!i.name||!i.standard)} onClick={()=>act(async()=>{const r=await call('/rules','POST',{name,items});setRuleId(r.id);setName('');})}>保存规则版本</button></details>}
 <div className="image-check-form"><label>规则<select value={ruleId} onChange={e=>setRuleId(e.target.value)}><option value="">请选择</option>{rules.map(r=><option key={r.id} value={r.id}>{r.name} · v{r.version}</option>)}</select></label><label>门店<input value={store} onChange={e=>setStore(e.target.value)} /></label><button disabled={busy||!ruleId||!store} onClick={()=>act(async()=>setTask(await call('/tasks','POST',{rule_id:ruleId,store})))}>创建核验任务</button></div>
 {task&&<div><h3>{task.rule.name} · {task.store}</h3><p>{labels[task.status]} {labels[task.conclusion]||''}</p>{task.rule.items.map(it=><fieldset key={it.id}><legend>{it.name}{it.required?' · 必检':''}</legend><p>标准：{it.standard}</p><p>{it.photo_hint}</p>{it.reference_id&&<img alt="参考标准" src={apiUrl('/api/image-checks/photos/'+it.reference_id)} />}{task.photos[it.id]&&<img alt="门店证据" src={apiUrl('/api/image-checks/photos/'+task.photos[it.id])} />}{task.status==='pending'&&<input type="file" accept="image/png,image/jpeg" disabled={busy} onChange={e=>{const file=e.target.files[0];if(file)act(async()=>{const p=await call('/photos','POST',file);setTask(await call('/tasks/'+task.id+'/photos','PUT',{...task.photos,[it.id]:p.id}));});}} />}{task.results[it.id]&&<p><strong>{labels[task.results[it.id].status]}</strong> · {task.results[it.id].reason}</p>}</fieldset>)}{task.error&&<p role="alert">{task.error}</p>}{['pending','failed'].includes(task.status)&&<button disabled={busy} onClick={()=>act(async()=>setTask(await call('/tasks/'+task.id+'/analyze','POST')))}>{busy?'处理中…':'开始 AI 核验'}</button>}</div>}
 <h3>核验记录</h3>{tasks.length===0?<p>暂无任务，请先配置规则并创建任务。</p>:tasks.map(t=><button key={t.id} disabled={busy} onClick={()=>setTask(t)}>{t.rule.name} · {t.store} · {labels[t.conclusion]||labels[t.status]}</button>)}
 </>}</section>;
}
