import React,{useState,useEffect} from 'react';
import {apiUrl} from './api';
import {Icon} from './icons';
import {isShowcaseMode} from './showcaseApi';
export const photoUrl=id=>isShowcaseMode?'/showcase/image-checks/photos/'+id+'.jpg':apiUrl('/api/image-checks/photos/'+id);
export async function configCall(path,method='GET',body){if(isShowcaseMode){if(method!=='GET')throw Error('展示版本不支持上传或AI分析');const response=await fetch('/showcase/image-checks.json');if(!response.ok)throw Error('核验快照读取失败');const snapshot=await response.json();return snapshot[path.slice(1)]||[];}const raw=body instanceof File;const r=await fetch(apiUrl('/api/image-checks'+path),{method,headers:body&&!raw?{'Content-Type':'application/json'}:{},body:body?(raw?body:JSON.stringify(body)):undefined});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'请求失败');return data;}
export function PhotoStandards({rule,onChange}){
 const [error,setError]=useState('');const defaults=[{id:'item-1',name:'',standard:'',photo_hint:'',required:true,reference_id:null}];const items=rule.photoItems?.length?rule.photoItems:defaults;
 const edit=(i,key,value)=>{const id=items[i]?.id;onChange(current=>({photoItems:(current.photoItems?.length?current.photoItems:defaults).map(x=>x.id===id?{...x,[key]:value}:x)}));};
 return <section className="photo-standards"><h3>图片检查项</h3>{error&&<p role="alert">{error}</p>}{items.map((it,i)=><fieldset key={it.id}><legend>检查项 {i+1}</legend><label>检查项名称<input value={it.name} onChange={e=>edit(i,'name',e.target.value)}/></label><label>通过标准<textarea value={it.standard} onChange={e=>edit(i,'standard',e.target.value)}/></label><label>拍摄要求<input value={it.photo_hint} onChange={e=>edit(i,'photo_hint',e.target.value)}/></label><label><input type="checkbox" checked={it.required} onChange={e=>edit(i,'required',e.target.checked)}/>必检项</label><div className="reference-upload"><span>标准参考图（可选）</span><label className="reference-upload-card">{it.reference_id?<img alt="标准参考图" src={photoUrl(it.reference_id)}/>:<Icon name="image" size={26}/>}<span>{it.reference_id?'点击更换参考图':'点击上传标准参考图'}</span><small>JPG、PNG，最大 10 MB</small><input type="file" accept="image/png,image/jpeg" onChange={async e=>{try{if(e.target.files[0]){const p=await configCall('/photos','POST',e.target.files[0]);edit(i,'reference_id',p.id);}}catch(e){setError(e.message);}}}/></label>{it.reference_id&&<button type="button" onClick={()=>edit(i,'reference_id',null)}>移除参考图</button>}</div><button onClick={()=>onChange({photoItems:items.filter((_,j)=>j!==i)})}>删除检查项</button></fieldset>)}<button disabled={items.length>=20} onClick={()=>onChange({photoItems:[...items,{id:'item-'+Date.now(),name:'',standard:'',photo_hint:'',required:true,reference_id:null}]})}>＋ 添加检查项</button></section>;
}
const labels={pass:'通过',fail:'不通过',review:'人工核查',need_photo:'待补充照片',pending:'待上传',analyzing:'分析中',completed:'已完成',failed:'分析失败'};
export function sampleMetrics(records){
 const labeled=records.filter(t=>['pass','fail'].includes(t.ground_truth));
 const comparable=labeled.filter(t=>t.status==='completed'&&['pass','fail'].includes(t.conclusion));
 const correct=comparable.filter(t=>t.conclusion===t.ground_truth).length;
 return {total:records.length,labeled:labeled.length,correct,comparable:comparable.length,accuracy:comparable.length?Math.round(correct/comparable.length*100):null};
}
const Btn=({primary=false,children,...props})=><button type="button" {...props} className={`prototype-rule-button prototype-rule-button--${primary?'primary':'secondary'} prototype-rule-button--sm`}>{children}</button>;
export function RuleSamples({rule,disabled,readOnly=false}){
 const [records,setRecords]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[expanded,setExpanded]=useState(null);
 const refresh=()=>configCall('/tasks').then(t=>setRecords(t.filter(x=>x.rule.source_config_id===rule.id)));
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[rule.id,disabled]);
 useEffect(()=>{if(disabled||!records.some(t=>t.status==='analyzing'))return;const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),3000);return ()=>clearInterval(timer);},[disabled,records,rule.id]);
 const act=async fn=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{await refresh().catch(e=>setError(e.message));setBusy(false);}};
 const isPhoto=rule.type==='image'&&(rule.params.inputType||'image')==='image', locked=disabled||readOnly||busy;
 const upload=files=>act(async()=>{
  const saved=(await configCall('/configs')).find(c=>c.id===rule.id);if(!saved||!saved.photoItems?.length)throw Error('请先保存图片检查标准');
  const version=await configCall('/rules','POST',{name:saved.name,items:saved.photoItems,source_config_id:saved.id,source_config_version:saved.version});
  for(const file of files){const photo=await configCall('/photos','POST',file);const t=await configCall('/tasks','POST',{rule_id:version.id,store:'规则样本测试',sample_name:file.name});await configCall('/tasks/'+t.id+'/photos','PUT',Object.fromEntries(version.items.map(i=>[i.id,photo.id])));}
 });
 const run=id=>act(async()=>{const request=configCall('/tasks/'+id+'/analyze','POST',{});setRecords(old=>old.map(t=>t.id===id?{...t,status:'analyzing'}:t));await request;});
 const m=sampleMetrics(records.filter(t=>t.rule.source_config_version===rule.version));
 return <div className="rule-samples prototype-sample-workspace">
 {error&&<p className="sample-error" role="alert">{error}</p>}
 <section className="sample-panel"><h3>样本测试概况</h3><div className="sample-stat-grid">{[['样本总数',m.total,'个'],['已标注',m.labeled,'个'],['AI 正确',m.correct,'个'],['准确率',m.accuracy??'—',m.accuracy===null?'':'%']].map(([name,value,unit])=><div key={name}><span>{name}</span><strong>{value}<small>{unit}</small></strong></div>)}</div><p className="sample-note">准确率仅根据已完成人工标注且 AI 明确判定通过或不通过的样本计算；人工核查和待补拍不计入分母。当前版本 {rule.version} 已对照 {m.comparable} 个样本；历史版本不计入准确率。</p></section>
 <section className="sample-upload-panel"><div className="sample-upload-icon"><Icon name="folder" size={32}/></div><h3>上传样本图片/视频</h3><p>{isPhoto?'支持 JPG、PNG，可多选上传':'此模板需要视频时序或业务数据，请使用视频分析任务验证'}</p>{isPhoto&&<label className={`prototype-rule-button prototype-rule-button--primary prototype-rule-button--sm ${locked?'sample-disabled':''}`}>{busy?'处理中…':'选择文件上传'}<input type="file" accept="image/png,image/jpeg" multiple disabled={locked||rule.id==='NEW'} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length)upload(files);}}/></label>}</section>
 <section className="sample-panel"><div className="sample-list-header"><h3>测试样本列表 <small>（{m.labeled}/{m.total} 已标注）</small></h3><Btn disabled={busy||disabled} onClick={()=>act(refresh)}>刷新</Btn></div>{!records.length?<div className="sample-empty"><Icon name="clipboard" size={32}/><p>暂无已保存的样本测试</p></div>:records.map(t=>{const pid=Object.values(t.photos)[0];const match=['pass','fail'].includes(t.conclusion)&&t.ground_truth?t.conclusion===t.ground_truth:null;return <div key={t.id} className="sample-row-wrap"><div className="sample-row">{pid&&<img className="sample-thumb" alt="样本照片" src={photoUrl(pid)}/>}<div className="sample-description"><strong>{t.sample_name||t.id}</strong><p>{t.rule.source_config_version||'历史版本'} · {labels[t.status]} · AI 判定：{labels[t.conclusion]||'尚未判定'}</p>{match!==null&&<span className={match?'sample-match':'sample-mismatch'}>{match?'与人工标注一致':'与人工标注不一致'}</span>}</div><select aria-label="人工预期结果" value={t.ground_truth||''} disabled={locked||t.status==='analyzing'} onChange={e=>act(()=>configCall('/tasks/'+t.id+'/label','PUT',{ground_truth:e.target.value||null}))}><option value="">待标注</option><option value="pass">预期通过</option><option value="fail">预期不通过</option></select>{['pending','failed'].includes(t.status)&&<Btn primary disabled={locked} onClick={()=>run(t.id)}>{t.status==='failed'?'重试':'AI 核验'}</Btn>}<Btn onClick={()=>setExpanded(expanded===t.id?null:t.id)}>详情</Btn></div>{expanded===t.id&&<div className="sample-result-detail">{t.error&&<p role="alert">{t.error}</p>}{t.rule.items.map(it=><div key={it.id}><strong>{it.name}</strong><p>标准：{it.standard}</p><p>{labels[t.results[it.id]?.status]||'尚未判定'} · {t.results[it.id]?.reason||''}</p></div>)}<p>模型调用 {t.usage?.length||0} 次 · {t.usage?.reduce((sum,u)=>sum+(u.total_tokens||0),0)||0} Token</p></div>}</div>;})}</section></div>;
}
